spring.application.name=QueueFlow API
server.port=8080
queueflow.api.version=v1

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

#Flyway
spring.flyway.enabled=true

# Guest join idempotency
queueflow.guest-token-encryption-key=${GUEST_TOKEN_ENCRYPTION_KEY}
queueflow.qr-credential-encryption-key=${QR_CREDENTIAL_ENCRYPTION_KEY}

# Web frontend
queueflow.web.allowed-origin=${WEB_ORIGIN:http://localhost:8000}