spring.application.name=QueueFlow API
server.port=8080
queueflow.api.version=v1

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

#Flyway
spring.flyway.enabled=true